{% set name = "ndvi2gif" %}
{% set version = "1.0.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4e29c8d3127cc7422aa49e71be12f446e6f82164aa653056787e12cb81863aa

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5
    - earthengine-api >=0.1.347
    - numpy <2.0
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - pillow
    - imageio
    - tqdm
    - requests
    - geopandas
    - fiona
    - pycrs
    - deims >=4.0
    - statsmodels >=0.13
    - scikit-learn >=1.0

test:
  imports:
    - ndvi2gif
    - ndvi2gif.s1_ard
    - ndvi2gif.timeseries
    - ndvi2gif.clasification
  requires:
    - python >={{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Multi-seasonal remote sensing and climate analysis suite with machine learning classification using Google Earth Engine
  description: |
    NDVI2GIF is a comprehensive Python library for multi-seasonal remote sensing and climate analysis using Google Earth Engine.
    Version 1.0.0 is the first stable release, expanding beyond vegetation monitoring into comprehensive climate analysis.

    Key features include:
    - 88 variables across 7 satellite and climate platforms (Sentinel-1/2/3, Landsat, MODIS, ERA5-Land, CHIRPS)
    - ERA5-Land climate reanalysis (47 variables, 1950-present): temperature, precipitation, soil moisture, radiation, wind
    - CHIRPS high-resolution precipitation (1981-present, ~5.5km)
    - 40+ vegetation and environmental indices with SAR preprocessing
    - 8 machine learning classification algorithms (supervised and unsupervised)
    - Time series analysis with trend detection and phenology metrics
    - Complete Jupyter Book documentation for research workflows
  doc_url: https://digdgeo.github.io/Ndvi2Gif/
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
