{% set name = "ndvi2gif" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22b8dec0043a28b64b995de059896d421f0b13e2b9083ceb36a01a1f2ead5c04

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - geemap >=0.6.10
    - python

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  # https://choosealicense.com/licenses/mit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create ndvi seasonal composites, and download them as gif and geotiff
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
