{% set name = "ndvi2gif" %}
{% set version = "0.1.5" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e4a78d16000f0156c7f2ad2c62bf81f4290a6907eedb101ac75595751d39939

build:
  noarch: python
  number: 0
  script: python -m pip install .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - matplotlib-base
    - pillow
    - imageio
    - tqdm
    - geemap >=0.29.5
    - earthengine-api >=0.1.347
    - geopandas
    - fiona
    - ipyleaflet
    - folium
    - ipywidgets

test:
  imports:
    - ndvi2gif
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate seasonal composites based on statistical summaries of available indices using Google Earth Engine and geemap
  description: |
    NDVI2GIF allows researchers to generate seasonal composites based on statistical summaries of available indices from Google Earth Engine. The package is not limited to vegetation indices and can work with any compatible remote sensing index available in GEE.
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
    
 