{% set name = "ndvi2gif" %}
{% set version = "0.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed426588f1af16283a96b304194a587170f812d84585e3408269ebe9c4f1f351

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5
    - earthengine-api >=0.1.347
    - numpy <2.0
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - pillow
    - imageio
    - tqdm
    - requests
    - geopandas
    - fiona
    - pycrs
    - deims >=4.0
    - statsmodels >=0.13
    - scikit-learn >=1.0

test:
  imports:
    - ndvi2gif
    - ndvi2gif.s1_ard
    - ndvi2gif.timeseries
    - ndvi2gif.clasification
  requires:
    - python >={{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Multi-seasonal remote sensing analysis suite: composites, SAR preprocessing, time series analytics, and land cover classification with Google Earth Engine
  description: |
    NDVI2GIF is a comprehensive Python library for multi-seasonal remote sensing analysis using Google Earth Engine.
    
    Key features in v0.6.0:
    - Seasonal composites for 40+ vegetation, water, and geological indices
    - SAR preprocessing with Sentinel-1 ARD processor  
    - Time series analysis with phenological metrics
    - NEW: Complete land cover classification module (supervised & unsupervised)
    - NEW: Enhanced export capabilities to Google Drive and Earth Engine Assets
    - 15+ classification algorithms including Random Forest, SVM, K-means
    - 95%+ documentation coverage with comprehensive examples
