{% set name = "ndvi2gif" %}
{% set version = "0.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed426588f1af16283a96b304194a587170f812d84585e3408269ebe9c4f1f351

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5
    - earthengine-api >=0.1.347
    - numpy <2.0
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - pillow
    - imageio
    - tqdm
    - requests
    - geopandas
    - fiona
    - pycrs
    - deims >=4.0
    - statsmodels >=0.13
    - scikit-learn >=1.0

test:
  imports:
    - ndvi2gif
    - ndvi2gif.s1_ard
    - ndvi2gif.timeseries
    - ndvi2gif.clasification
  requires:
    - python >={{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Multi-seasonal remote sensing analysis suite with machine learning classification using Google Earth Engine
  description: |
    NDVI2GIF is a comprehensive Python library for multi-seasonal remote sensing analysis using Google Earth Engine.
    This version adds complete land cover classification capabilities with supervised and unsupervised algorithms,
    enhanced export features to Google Drive and Earth Engine Assets, and comprehensive documentation coverage.
    
    Features include seasonal composites for 40+ vegetation indices, SAR preprocessing with Sentinel-1 ARD processor,
    time series analysis with phenological metrics, 15+ classification algorithms including Random Forest and SVM,
    and advanced export capabilities for research workflows.
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
