{% set name = "ndvi2gif" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e4a78d16000f0156c7f2ad2c62bf81f4290a6907eedb101ac75595751d39939

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.7
    - geemap ==0.29.5

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  # https://choosealicense.com/licenses/mit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create ndvi seasonal composites, and download them as gif and geotiff
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
