{% set name = "ndvi2gif" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b906c702f1e0e9c05b0ca8182b4781c9cb468da95517c7892eec60cc60484474

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - geemap >=0.6.10
    - python

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  # https://choosealicense.com/licenses/mit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create ndvi seasonal composites, and download them as gif and geotiff
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
