{% set name = "ndvi2gif" %}
{% set version = "0.1.4" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e2f10d19589ba0ef3e9c6f3db268fc26143fba521ed7a0cb937e61a7091b77a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - geemap >=0.29.5

test:
  imports:
    - ndvi2gif

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to create NDVI seasonal composites, and download them as GIF and GeoTIFF
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
