{% set name = "ndvi2gif" %}
{% set version = "0.5.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15cedbf16628d6a8ec7b96cc0270adce5a143289638773152eb79a1dae9de490

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geemap >=0.29.5
    - earthengine-api >=0.1.347
    - numpy <2.0
    - pandas
    - scipy
    - matplotlib-base
    - seaborn
    - pillow
    - imageio
    - tqdm
    - requests
    - geopandas
    - fiona
    - pycrs
    - deims >=4.0
    - statsmodels >=0.13
    - scikit-learn >=1.0

test:
  imports:
    - ndvi2gif
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/Digdgeo/Ndvi2Gif
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate seasonal composites based on statistical summaries of available indices using Google Earth Engine and Geemap
  description: |
    NDVI2GIF allows researchers to generate multi seasonal composites based on statistical summaries of available Earth Observation indices. The package is not limited to vegetation indices and can work with any compatible remote sensing index available in GEE.
  doc_url: https://github.com/Digdgeo/Ndvi2Gif
  dev_url: https://github.com/Digdgeo/Ndvi2Gif

extra:
  recipe-maintainers:
    - Digdgeo
